language: go

go:
  - "1.11.x"

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
    - PGUSER=postgres
    - PGHOST=""
    - PGPORT=5433
    - GO_ENV=test

services:
  - postgresql

before_script:
  - psql -c 'create database glapi_test;' -U postgres
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets

install:
  - go get github.com/gobuffalo/buffalo/buffalo
  - go get github.com/golang/dep/cmd/dep
  - dep ensure

script: buffalo test
